version: "3.9"

services:
  server_test:
    container_name: server-test
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
      target: Builder
    command: go run ./app/cmd/server/main.go
    env_file:
      - .env.test
    volumes:
      - type: bind
        source: app
        target: /go/src/app
    depends_on:
      migrate_test:
        condition: service_completed_successfully

  migrate_test:
    container_name: migrate-test
    build:
      context: .
      dockerfile: ./docker/migration/Dockerfile
      target: Builder
    command: go run ./app/cmd/migration/main.go
    env_file:
      - .env.test
    volumes:
      - type: bind
        source: app
        target: /go/src/app
    depends_on:
      db_test:
        condition: service_healthy

  db_test:
    container_name: mysql-test
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      retries: 20
    tmpfs:
      - /var/lib/mysql
    volumes:
      - type: volume
        source: mysql-volume
        target: /var/lib/mysql

volumes:
  mysql-volume:
